version: '3.8'
services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - ./.env

  web:
    build: .
    restart: always
    depends_on: 
      - db
    ports: 
      - 3000:8000
    env_file:
      - ./.env

volumes:
  postgres_data:      